### ISSUE TITLE
Add eslint-plugin-promise

### ISSUE THREAD

**Issue by aaarichter** [groupon/javascript#33]
this might be helpful https://www.npmjs.com/package/eslint-plugin-promise 😉

**Comment by dbushong** [comment]
Possibly.  Let's look https://github.com/xjamundx/eslint-plugin-promise#rules :

### `catch-or-return`

default: error
my take: error

I'd have to think about it, but this is probably a win?

### `no-return-wrap`

default: error
my take: error

Seems good.

### `param-names`

default: error
my take: error

While this is problematic due to shadowing if you have a nested set of
`new Promise()` invocations, we probably shouldn't be doing that anyway
(move the inner one into another function)

### `always-return`

default: error
my take: **off**

There's a number of cases where you might only care about promise resolution/
rejection, but not the actual resolved value (in timing/sequencing cases) -
forcing people to `return undefined;` or something would be meh.

Also, the inconsistent return example they give will already be caught by
our use of the `consistent-return` rule.

### `no-native`

default: off
my take: off

### `no-nesting`

default: warn
my take: **off**

Occasionally needed for proper variable scoping.  Maybe once we are only
supporting environments with async/await, we can add this to encourage
refactoring to less complicated structures.

### `no-promise-in-callback` / `no-callback-in-promise`

default: warn
my take: **off**

As we're in the process of converting a bunch of callback code, this sort
of interplay is going to be inevitable for the time being - let's not complain
about it.

### `avoid-new`

default: warn
my take: **off**

Nah.  Native `new Promise()` is just fine - there's already `util.promisify`
for common cases, so anywhere else we're still `new Promise()` is ok.

### `no-new-statics`

default: error
my take: error

:+1:

### `no-return-in-finally`

default: warning
my take: **error**

### `valid-params`

default: warning
my take: **error**

### `prefer-await-to-then` / `prefer-await-to-callbacks`

default: ?
my take: **off**

Not yet.

**Comment by jkrems** [comment]
`prefer-await-to-*` would be interesting if it was a fixable rule. Otherwise it's just noise, especially in bigger projects.
